### PR TITLE
Fix - Bump @types/node from 16.7.5 to 17.0.8

### PR DESCRIPTION
**Pull request by flacial**
Fix the issues when updating to v17.0.8.

Issue:

URLSearchParams arguments can't be `type | undefined`

```
helpers/discordAuth.ts(65,31): error TS2345: Argument of type '{ grant_type: string; client_id: string | undefined; client_secret: string | undefined; code: string; redirect_uri: string | undefined; scope: string; }' is not assignable to parameter of type 'string | URLSearchParams | Record<string, string | readonly string[]> | Iterable<[string, string]> | readonly [string, string][] | undefined'.
```

### CODE REVIEW

**Comment by JasirZaeem** [comment]
The types being used should correspond to the library being used, or the node engine in case of @types/node. We are using 14 on vercel I don't think we need to update types to node 17

**Comment by flacial** [comment]
> The types being used should correspond to the library being used, or the node engine in case of @types/node. We are using 14 on vercel I don't think we need to update types to node 17

I just did some research and what you said makes sense. 

According to what you said, we should let the library handle updating node types?

File: helpers/discordAuth.ts [hunk 1]
```diff
@@ -99,19 +95,21 @@ const getTokenFromRefreshToken = (
       grant_type: 'refresh_token',
       refresh_token
     })
-  }).then(r => r.json())
+  })
+  return await r.json()
```
Comment (songz) [inline helpers/discordAuth.ts:99]: I don't think its right to do `return await <promise>` because the nature of `async` will return a promise already so we don't have to wait for the last promise to resolve before returning.

```js
return r.json()
``` 

should suffice. same with the rest.

**Comment by songz** [comment]
we could upgrade node to v17: https://vercel.com/docs/runtimes#official-runtimes/node-js/node-js-version

**Comment by songz** [comment]
Actually just checked, vercel only supports v14.

 good catch @JasirZaeem ! Thanks.

Updated our docs so we know about this in the future: https://github.com/garageScript/c0d3-app/wiki/Dependabot#notes

I vote to close this.

**Comment by flacial** [comment]
Closed it as NextJS only supports node v14.
